[build]
command = "cd functions/go-serverless && go build && mv go-serverless ../go-serverless-fn && cd ../rust-serverless && make build && cd ../../ && node redirects.js"
publish = "public"
functions = "functions"
